title: F. Melih Dal
email: ferhatmelih@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal home page of Ferhat Melih Dal. I am an engineer and researcher. 
  I share anything I am interestered on this page. 
baseurl: ""
url: "https://ferhatmelih.github.io" 
twitter_username: fmelihdal
github_username:  ferhatmelih

author: F. Melih Dal
avatar: /pics/profile.png

plugins:
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton

